# 3 NumPy

## 1

In [18]:
import numpy as np
arr = np.random.randint(20,size = (3,4,2))

In [19]:
print(arr)

[[[ 0  5]
  [13  9]
  [10  4]
  [ 4  2]]

 [[ 6  2]
  [19 13]
  [ 0 13]
  [ 5  3]]

 [[10 10]
  [ 5  9]
  [16 12]
  [ 7  4]]]


In [28]:
arr[0,1,1]

9

In [29]:
arr[0]

array([[ 0,  5],
       [13,  9],
       [10,  4],
       [ 4,  2]])

In [31]:
arr[0:2]

array([[[ 0,  5],
        [13,  9],
        [10,  4],
        [ 4,  2]],

       [[ 6,  2],
        [19, 13],
        [ 0, 13],
        [ 5,  3]]])

In [39]:
arr[0:2,0:4:2,1]

array([[ 5,  4],
       [ 2, 13]])

## 2

In [69]:
import time

In [80]:
array = list(range(250000))

In [103]:
nparr = np.array(array)

In [140]:
times = []
timesnp = []
for i in range(100):
    
    time1 = time.time()
    array2 = list([x*2 for x in array])
    times.append(time.time()- time1)
    
    time1 = time.time()
    nparr2 = nparr * 2
    timesnp.append(time.time()- time1)
    
print ("Время для list: {0}".format(np.mean(times)))
print ("Время для nparray: {0}".format(np.mean(timesnp)))
print ("Разница во времени выполнения в {0} раз".format(round(np.mean(times)/np.mean(timesnp))))

Время для list: 0.02788762331008911
Время для nparray: 0.0003160381317138672
Разница во времени выполнения в 88.0 раз


# 3

In [160]:
# np.linspace()
start = 0
stop = 10**5
num = 10**5+1



times = []
timesnp = []
for i in range(100):
    
    time1 = time.time()
    myLinspace = [start + stop/(num-1) * i for i in range(num)]
    times.append(time.time()- time1)
    
    time1 = time.time()
    nplinspace = np.linspace(start,stop,num)
    timesnp.append(time.time()- time1)
    
print ("Время для myLinspace: {0}".format(np.mean(times)))
print ("Время для npLinspace: {0}".format(np.mean(timesnp)))
print ("Разница во времени выполнения в {0} раз".format(round(np.mean(times)/np.mean(timesnp))))


Время для myLinspace: 0.03471694707870483
Время для npLinspace: 0.0004723858833312988
Разница во времени выполнения в 73.0 раз
